language: generic

sudo: required

cache:
    apt: true

matrix:
    include:
    - env: CXX=clang++-7 CC=clang-7
      addons:
        apt:
          packages:
            - clang-7
            - g++-7 # For the standard library
            - cmake
          sources: &sources
            - sourceline: deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main
              key_url: https://%{app_host}/files/gpg/llvm-toolchain-trusty.asc
            - ubuntu-toolchain-r-test
    - env: CXX=clang++-6.0 CC=clang-6.0
      addons:
        apt:
          packages:
            - clang-6.0
            - g++-7 # For the standard library
            - cmake
          sources: &sources
            - ubuntu-toolchain-r-test
    - env: CXX=clang++-5.0 CC=clang-5.0
      addons:
        apt:
          packages:
            - clang-5.0
            - g++-7 # For the standard library
            - cmake
          sources: &sources
            - ubuntu-toolchain-r-test
    - env: CXX=g++-8 CC=gcc-8
      addons:
        apt:
          packages:
            - g++-8
            - cmake
          sources: &sources
            - ubuntu-toolchain-r-test
    - env: CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - g++-7
            - cmake
          sources: &sources
            - ubuntu-toolchain-r-test

script:
    - mkdir build && cd build
    - cmake ..
    - make
    - ./cpp11training
    - cd ..
    - cd coupling
    - mkdir build && cd build
    - cmake ..
    - make
    - ./coupled_program
    - cd ..

